---
- name: Stop systemd-resolved
  service:
    name: systemd-resolved
    state: stopped



- name: Copy resolv.conf file and change DNS configuration
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
