- name: Ensure nginx is installed and in working state
  apt:
    name: nginx
    state: latest


- name: copy the nginx config file and restart nginx
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
#    validate: nginx -t -c %s
  notify: restart nginx


- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes 
