---
- name: Install HAProxy
  apt:
    name: haproxy

- name: Config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: 
    - Restart HAProxy

- name: start HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes

- name: HAProxy exporter setup for vm1
  docker_container:
    name: haproxy_exporter
    image: quay.io/prometheus/haproxy-exporter:v0.9.0
    ports:
      - "9101:9101"
    command: --haproxy.scrape-uri="http://vm1:88/haproxy?stats;csv"
  when: inventory_hostname == "vm1"

- name: HAProxy exporter setup for vm2
  docker_container:
    name: haproxy_exporter
    image: quay.io/prometheus/haproxy-exporter:v0.9.0
    ports:
      - "9101:9101"
    command: --haproxy.scrape-uri="http://vm2:88/haproxy?stats;csv"
  when: inventory_hostname == "vm22"
