---
 - name: Install InfluxDB
   apt:
     name:
      -  influxdb
      -  influxdb-client
     state: latest


 - name: Download Telegraf package
   get_url:
     url: https://dl.influxdata.com/telegraf/releases/telegraf_1.15.3-1_amd64.deb
     dest: /opt/telegraf_1.15.3-1_amd64.deb

 - name: Install Telegraf Package
   apt:
     deb: /opt/telegraf_1.15.3-1_amd64.deb

 - name: Telegraf config
   template:
     src: telegraf.conf.j2
     dest: /etc/telegraf/telegraf.conf
   notify:
     - Restart telegraf


 - name: Force all notified handlers to run at this point, not waiting for normal sync points
   meta: flush_handlers


 - name: Start service influxdb, if not started
   service:
     name: influxdb
     state: started
     enabled: yes


 - name: Start service Telegraf, if not started
   service:
     name: telegraf
     state: started
     enabled: yes
