---
- name: Add user agama
  user:
    name: agama
    system: yes

- name: Create directory
  file:
    state: directory
    path: /opt/agama
    owner: agama
    group: agama
    mode: '0755'

- name: Install python dependencies
  package: 
    name:
      - python3-flask-sqlalchemy
      - python3-pymysql
    state: latest


- name: Download agama.py
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama
    owner: agama
    group: agama
    mode: '0755'
