---
- name: Add user "backup" and generate SSH key
  user:
    name: backup
    shell: /bin/bash
    home: /home/backup
    generate_ssh_key: yes

# Add MySQL backup user and MySQL cnf file

- name: Create MySQL backup user
  mysql_user:
    name: "{{ mysql_backup_user }}"
    password: "{{ mysql_backup_pass }}"
    priv: "{{ mysql_database }}.*:SELECT,LOCK TABLES"
    host: "localhost"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
  when: inventory_hostname == "vm2"

- name: Copy MySQL configuration file
  template:
    src: backup.my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    group: backup
    mode: '0400'
  when: inventory_hostname == "vm2"

# Configure backup user's groups
- name: Add group Grafana
  group:
    name: grafana
    state: present
  when: inventory_hostname == groups['grafana'][0]



- name: Add the user to the Grafana group on the vm3
  user:
    name: backup
    groups: grafana
  when: inventory_hostname == "vm3"


#- name: Add the user to the Grafana group on the VM1
#  user:
#    name: backup
#    groups: grafana
#  when: inventory_hostname == "vm1"



- name: Add the user to the MySQL group on the VM2
  user:
    name: backup
    groups: mysql
  when: inventory_hostname == "vm2"



# Task to create required directories and backup scripts

- name: Create backup, restore and scripts directories
  file:
    path: /home/backup/{{ item }}
    state: directory
    owner: backup
    group: backup
    mode: '0755'
  loop:
    - backup
    - restore
    - scripts


- name: Copy Grafana backup script to vm3
  copy:
    src: "{{ item }}"
    dest: /home/backup/backup/{{ item }}
    owner: backup
    group: backup
    mode: '0500'
  when: inventory_hostname == "vm3"
  loop:
    - grafana.sh


- name: Copy MySQL backup scripts to VM2
  copy:
    src: "{{ item }}"
    dest: /home/backup/backup/{{ item }}
    owner: backup
    group: backup
    mode: '0500'
  when: inventory_hostname == "vm2"
  loop:
    - mysql.sh



# Install Duplicity and copy crontabs

- name: Install Duplicity
  apt:
    name: duplicity
    state: latest

- name: Copy crontab to VM1
  template:
    src: crontab.vm1.j2
    dest: /etc/cron.d/backup
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == "vm1"

- name: Copy crontab to VM2
  template:
    src: crontab.vm2.j2
    dest: /etc/cron.d/backup
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == "vm2"

- name: Copy crontab to VM3
  template:
    src: crontab.vm3.j2
    dest: /etc/cron.d/backup
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == "vm3"
