---
- name: Install Exporter packages
  apt:
    name:
      - prometheus-node-exporter
    state: latest

- name: Start service prometheus-node-exporter
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes
