---
  - name: adds user with name juri
    user:
       name: 'juri'

  - name: adds user with name roman
    user:
       name: 'roman' 

  - name: adds ssh authorization for juri
    authorized_key:
      user: juri
      state: present
      key: https://github.com/hudolejev.keys

  - name: adds ssh authorization for roman
    authorized_key:
      user: roman
      state: present
      key: https://github.com/romankuchin.keys

