---
 - name: Install fping
   apt:
     name: fping
     state: latest

 - name: Install curl
   apt:
     name: curl
     state: latest

 - name: Add the user "pinger"
   user:
     name: pinger

 - name: Create pinger configuration directory
   file:
     path: /etc/pinger
     state: directory
     mode: '0751'

 - name: Configure Pinger config
   template:
     src: pinger.conf.j2
     dest: /etc/pinger/pinger.conf
     mode: '0755'


 - name: Setup pinger script
   template:
     src: pinger.sh.j2
     dest: /usr/local/bin/pinger
     mode: '0755'

 - name: Create pinger service
   template:
     src: pinger.service.j2
     dest: /etc/systemd/system/pinger.service
   notify:
     - Reload systemd
     - Restart pinger

 - name: Force all notified handlers to run at this point, not waiting for normal sync points
   meta: flush_handlers

 - name: Start service pinger, if not started
   service:
     name: pinger
     state: started
     enabled: yes
