---
- name: Download
  unarchive:
      src: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.8.0/nginx-prometheus-exporter-0.8.0-linux-amd64.tar.gz
      dest: /usr/local/bin
      remote_src: yes

- name: Servisizing
  template:
      src: nginx-prometheus-exporter.service.j2
      dest: /etc/systemd/system/nginx-prometheus-exporter.service
  notify:
      - Systemctl daemon-reload
      - Restart nginx-prometheus-exporter

- name: Start service nginx-exporter, if not started
  service:
      name: nginx-prometheus-exporter
      state: started
      enabled: yes
